### ISSUE TITLE
Unable to use the module in lazy-load mode

### ISSUE THREAD

**Issue by gmarab** [PxyUp/ng-virtual-table#16]
First of all congratulations for your work: really great.

Unfortunately there is a problem that prevents me from using it in a large project that I am building.

The project is implemented in a lazy-loading mode, and I could not understand how and where to make the declaration of the ng-virtual-table module.

Declaring ng-virtual-table in the app.module you get the error:

ERROR Error: Template parse errors:
Can't bind to 'config' since it isn't a known property of 'ng-virtual-table'.
1. If 'config' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.

although commonmodule is defined both in app.module and in component.module.

Declaring ng-virtual-table in the component.module you get the error:

ERROR Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

Although in the component.module it is declared CommonModule but not BrowserModule.

Is ng-virtual-table usable in lazy-loading mode?

Thanks in advance

**Comment by PxyUp** [comment]
@gmarab Hi, thank you, for issue. Was fixed in new version.
Correct way to import, i removed `forRoot`
```javascript
imports: [
   ...,
   NgVirtualTableModule,
   ...
]
```

**Comment by PxyUp** [comment]
https://github.com/PxyUp/ng-virtual-table/commit/bf5eb7bdfbf11b15f6b8693cf780d82898c77880
