### ISSUE TITLE
NullInjectorError when JIT or AOT optimization is used or in production mode

### ISSUE THREAD

**Issue by Grajon** [PxyUp/ng-virtual-table#17]
Hi,
when a custom component is used (and declared with componentConstructor) and the AOT or JIT optimization is activated or when you are in production mode (with `ng build --prod`), a NullInjectorError occured :

```
ERROR NullInjectorError: StaticInjectorError(AppModule)[DynamicDirective -> InjectionToken ComponentInjector]: 
  StaticInjectorError(Platform: core)[DynamicDirective -> InjectionToken ComponentInjector]
```

I think the problem is in the **imports** declaration in **ngVirtualTable.module.ts** with :
`DynamicModule.withComponents([])`

no dynamic component declared here.

Thanks for your help on this great library, and sorry for my poor english...

**Comment by PxyUp** [comment]
Hi, can you create sandbox in stackblitz, I will be check. Which version of angular do you use?

**Comment by Grajon** [comment]
Don't know if it's relevent here to do it on stackblitz, and I don't know how to activate AOT in stackblitz...
The version is Angular 8 (tested on 8.0 and 8.2)
I've made a test with a modification on this code with a base class declared and used in DynamicModule.withComponents([MyNewBaseClass])
My component, used in componentConstructor, extends this MyNewBaseClass and all works fine :)

**Comment by PxyUp** [comment]
Free for MR;)

**Comment by PxyUp** [comment]
@Grajon was fixed in new release
